// <auto-generated />
using System;
using EscolaDeCursos.WebApp.Compartilhado.Infraestrutura.Orm;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscolaDeCursos.WebApp.Migrations
{
    [DbContext(typeof(EscolaDeCursosDbContext))]
    [Migration("20260924230837_Add_TBTurmas_TBMatriculas")]
    partial class Add_TBTurmas_TBMatriculas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloAluno.Dominio.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroMatricula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroMatricula")
                        .IsUnique();

                    b.ToTable("TBAlunos", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloCurso.Dominio.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DuracaoEmMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId", "Nome")
                        .IsUnique();

                    b.HasIndex("CursoId", "Ordem")
                        .IsUnique();

                    b.ToTable("TBAulas", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloCurso.Dominio.Curso", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CargaHoraria")
                        .HasColumnType("int");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TBCursos", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloInstrutor.Dominio.Instrutor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Telefone")
                        .IsUnique();

                    b.ToTable("TBInstrutores", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloMatricula.Dominio.Matricula", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurmaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TurmaId", "AlunoId")
                        .IsUnique();

                    b.ToTable("TBMatriculas", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloTurma.Dominio.Turma", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly>("DataTermino")
                        .HasColumnType("date");

                    b.Property<Guid>("InstrutorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NumeroMaximoAlunos")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("InstrutorId");

                    b.ToTable("TBTurmas", (string)null);
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloCurso.Dominio.Aula", b =>
                {
                    b.HasOne("EscolaDeCursos.WebApp.Modulos.ModuloCurso.Dominio.Curso", "Curso")
                        .WithMany("Aulas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBAulas_TBCurso");

                    b.Navigation("Curso");
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloMatricula.Dominio.Matricula", b =>
                {
                    b.HasOne("EscolaDeCursos.WebApp.Modulos.ModuloAluno.Dominio.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBMatriculas_TBAlunos");

                    b.HasOne("EscolaDeCursos.WebApp.Modulos.ModuloTurma.Dominio.Turma", "Turma")
                        .WithMany("Matriculas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBMatriculas_TBTurmas");

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloTurma.Dominio.Turma", b =>
                {
                    b.HasOne("EscolaDeCursos.WebApp.Modulos.ModuloCurso.Dominio.Curso", "Curso")
                        .WithMany("Turmas")
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBTurmas_TBCursos");

                    b.HasOne("EscolaDeCursos.WebApp.Modulos.ModuloInstrutor.Dominio.Instrutor", "Instrutor")
                        .WithMany("Turmas")
                        .HasForeignKey("InstrutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_TBTurmas_TBInstrutores");

                    b.Navigation("Curso");

                    b.Navigation("Instrutor");
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloCurso.Dominio.Curso", b =>
                {
                    b.Navigation("Aulas");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloInstrutor.Dominio.Instrutor", b =>
                {
                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("EscolaDeCursos.WebApp.Modulos.ModuloTurma.Dominio.Turma", b =>
                {
                    b.Navigation("Matriculas");
                });
#pragma warning restore 612, 618
        }
    }
}
